name: EvenMoreFish
author: Oheers
version: ${project.version}
main: com.oheers.fish.EvenMoreFish
api-version: 1.16
depend: [ Vault ]
softdepend: [ WorldGuard, PlaceholderAPI ]
loadbefore: [ AntiAC ]

commands:
  fish:
    usage: /<command> [name]





#  There are roughly 300-400 moose roaming freely in the woods of Sweden